"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/browser";

type ClassRow = { id:number; name:string; invite_code:string; created_at:string };
export default function ClassesPage() {
  const supabase=createClient(); const [classes,setClasses]=useState<ClassRow[]>([]); const [name,setName]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  async function loadClasses() { if(!supabase){setError("请先配置 Supabase 环境变量。");setLoading(false);return;} const {data,error:queryError}=await supabase.from("classes").select("id,name,invite_code,created_at").order("created_at",{ascending:false}); if(queryError)setError(queryError.message);else setClasses((data??[]) as ClassRow[]);setLoading(false); }
  useEffect(()=>{void loadClasses();},[]);
  async function createClass(event:FormEvent<HTMLFormElement>) { event.preventDefault();setError("");setMessage("");if(!supabase){setError("请先配置 Supabase 环境变量。");return;}const {data:{user}}=await supabase.auth.getUser();if(!user){setError("请先登录教师账号。");return;}const {error:insertError}=await supabase.from("classes").insert({name:name.trim(),teacher_id:user.id});if(insertError){setError(insertError.message);return;}setName("");setMessage("班级创建成功，邀请码已自动生成。");await loadClasses(); }
  return <><header className="topbar"><div><p className="eyebrow">Class management</p><h1>班级管理</h1><p className="muted">创建班级并把邀请码发给学生。</p></div></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<section className="grid two-col"><div className="card"><div className="card-header"><h2>创建班级</h2></div><form className="form" onSubmit={createClass}><div className="field"><label htmlFor="class-name">班级名称</label><input id="class-name" required maxLength={80} placeholder="例如：2026 春季 大物实验 1 班" value={name} onChange={(e)=>setName(e.target.value)} /></div><button className="button">创建并生成邀请码</button></form></div><div className="card"><div className="card-header"><h2>使用说明</h2></div><p className="notice">邀请码只用于学生加入班级。学生加入后，教师可以在报告检查页查看该班级的报告。</p></div></section><section className="card" style={{marginTop:18}}><div className="card-header"><h2>我的班级</h2><span className="muted small">{classes.length} 个班级</span></div>{loading?<div className="empty">正在加载…</div>:classes.length===0?<div className="empty">还没有班级，请先创建一个。</div>:<div className="table-wrap"><table><thead><tr><th>班级名称</th><th>邀请码</th><th>创建时间</th></tr></thead><tbody>{classes.map((item)=><tr key={item.id}><td>{item.name}</td><td><span className="code">{item.invite_code}</span></td><td>{new Date(item.created_at).toLocaleString("zh-CN")}</td></tr>)}</tbody></table></div>}</section></>;
}
