"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/browser";

type ReportRow={id:number;status:"draft"|"submitted"|"graded";teacher_score:number|null;teacher_comment:string|null;ai_suggestion:string|null;final_content:string|null;raw_data:unknown;calculation:unknown;created_at:string;submitted_at:string|null;graded_at:string|null;tasks:{class_id:number;classes:{name:string};experiments:{name:string}};student_id:string;users:{name:string}|null};
export default function ReportsPage(){
  const supabase=createClient();const [reports,setReports]=useState<ReportRow[]>([]);const [statusFilter,setStatusFilter]=useState("all");const [selectedId,setSelectedId]=useState<number|null>(null);const [score,setScore]=useState("");const [comment,setComment]=useState("");const [aiSuggestion,setAiSuggestion]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);const [aiLoading,setAiLoading]=useState(false);
  async function loadReports(){if(!supabase){setError("请先配置 Supabase 环境变量。");setLoading(false);return;}const {data,error:queryError}=await supabase.from("reports").select("id,student_id,status,teacher_score,teacher_comment,ai_suggestion,final_content,raw_data,calculation,created_at,submitted_at,graded_at,users(name),tasks!inner(class_id,classes!inner(name),experiments!inner(name))").order("created_at",{ascending:false});if(queryError)setError(queryError.message);else setReports((data??[]) as unknown as ReportRow[]);setLoading(false);}
  useEffect(()=>{void loadReports();},[]);const filtered=useMemo(()=>statusFilter==="all"?reports:reports.filter((item)=>item.status===statusFilter),[reports,statusFilter]);const selected=reports.find((item)=>item.id===selectedId)??null;
  function selectReport(report:ReportRow){setSelectedId(report.id);setScore(report.teacher_score==null?"":String(report.teacher_score));setComment(report.teacher_comment??"");setAiSuggestion(report.ai_suggestion??"");setMessage("");setError("");}
  async function requestAiCheck(){if(!selected)return;setAiLoading(true);setError("");setMessage("");try{const response=await fetch("/api/ai/check-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportId:selected.id})});const payload=await response.json();if(!response.ok){setError(payload.error??"AI 批改失败");return;}setAiSuggestion(payload.suggestion);setMessage("AI 批改建议已生成。");await loadReports();}catch{setError("AI 请求失败，请检查网络后重试。");}finally{setAiLoading(false);}}
  async function saveGrade(){if(!supabase||!selected)return;setError("");setMessage("");if(selected.status==="draft"){setError("学生尚未提交报告，暂时不能批改。");return;}const numericScore=score.trim()===""?null:Number(score);if(numericScore!==null&&(!Number.isFinite(numericScore)||numericScore<0||numericScore>100)){setError("分数请输入 0 到 100 之间的数字。");return;}const {error:updateError}=await supabase.from("reports").update({teacher_score:numericScore,teacher_comment:comment.trim()||null,status:"graded"}).eq("id",selected.id);if(updateError){setError(updateError.message);return;}setMessage("评分和评语已保存。");await loadReports();}
  return <><header className="topbar"><div><p className="eyebrow">Report review</p><h1>报告检查</h1><p className="muted">查看学生数据和报告，使用 AI 建议辅助批改。</p></div></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<section className="grid two-col"><div className="card"><div className="card-header"><h2>报告列表</h2><select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)}><option value="all">全部状态</option><option value="submitted">待批改</option><option value="graded">已批改</option><option value="draft">草稿</option></select></div>{loading?<div className="empty">正在加载…</div>:filtered.length===0?<div className="empty">暂无符合条件的报告。</div>:<div className="table-wrap"><table><thead><tr><th>实验 / 班级</th><th>学生</th><th>状态</th><th>提交时间</th></tr></thead><tbody>{filtered.map((report)=><tr key={report.id} onClick={()=>selectReport(report)} style={{cursor:"pointer",background:selectedId===report.id?"#f2f5ff":undefined}}><td><strong>{report.tasks.experiments.name}</strong><br/><span className="muted small">{report.tasks.classes.name}</span></td><td>{report.users?.name||report.student_id.slice(0,8)}</td><td><span className={`badge ${report.status}`}>{report.status==="submitted"?"待批改":report.status==="graded"?"已批改":"草稿"}</span></td><td>{report.submitted_at?new Date(report.submitted_at).toLocaleString("zh-CN"):"未提交"}</td></tr>)}</tbody></table></div>}</div><div className="card"><div className="card-header"><h2>报告详情</h2></div>{!selected?<div className="empty">选择左侧报告查看详情。</div>:<div className="form"><div><div className="muted small">实验</div><strong>{selected.tasks.experiments.name}</strong></div><div><div className="muted small">学生</div><span className="small">{selected.users?.name||selected.student_id}</span></div><div><div className="muted small">原始数据</div><div className="report-content">{JSON.stringify(selected.raw_data,null,2)}</div></div><div><div className="muted small">计算结果</div><div className="report-content">{JSON.stringify(selected.calculation,null,2)}</div></div><div><div className="muted small">学生最终报告</div><div className="report-content">{selected.final_content||"学生尚未提交最终内容。"}</div></div><div className="form-actions"><button className="button secondary" onClick={requestAiCheck} disabled={aiLoading}>{aiLoading?"分析中…":"AI 辅助检查"}</button></div>{aiSuggestion&&<div><div className="muted small">AI 建议</div><div className="report-content">{aiSuggestion}</div></div>}<div className="field"><label htmlFor="score">教师评分（0–100）</label><input id="score" type="number" min="0" max="100" value={score} onChange={(e)=>setScore(e.target.value)}/></div><div className="field"><label htmlFor="comment">教师评语</label><textarea id="comment" value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="填写最终评语和改进建议"/></div><button className="button" onClick={saveGrade}>保存评分和评语</button></div>}</div></section></>;
}
